import { db } from '../db';
import { todosTable } from '../db/schema';
import { type CreateTodoInput, type Todo } from '../schema';

export async function createTodo(input: CreateTodoInput): Promise<Todo> {
  try {
    // Insert todo record with proper field mapping
    const result = await db.insert(todosTable)
      .values({
        title: input.title,
        description: input.description || null,
        completed: false, // Default value as specified in schema
        // created_at and updated_at will be auto-generated by database defaults
      })
      .returning()
      .execute();

    // Return the created todo - no type conversions needed since no numeric fields
    return result[0];
  } catch (error) {
    console.error('Todo creation failed:', error);
    throw error;
  }
}